cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<int:product_id>', views.cart_remove, name='cart_remove'),
    path('add/<int:product_id>', views.cart_add, name='cart_add'),
]

catalog/urls.py
from django.urls import path
from . import views

app_name = 'catalog'

urlpatterns = [
    path('', views.home, name='home'),
    path('product-list/', views.product_list, name='product_list'),
    path('product-list/<slug:category_slug>/',
         views.product_list, name='product_list_by_category'),
    path('product-detail/<int:id>/<slug:slug>/',
         views.product_detail, name='product_detail'),
]

marketplace/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from rest_framework_jwt.views import (obtain_jwt_token,
                                      verify_jwt_token,
                                      refresh_jwt_token)

from catalog.api.views import (
    APIRoot,
    CategoryListAPIView,
    CategoryDetailAPIView,
    ProductListAPIView,
    ProductDetailAPIView,
    ProductCreateAPIView,
    ProductDetailUpdateAPIView,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('', include('catalog.urls', namespace='catalog')),
    path('social-auth/', include('social_django.urls', namespace='social')),
]

urlpatterns += [
    path('api/', APIRoot.as_view(), name='api_root'),

    path('api/jwt/', obtain_jwt_token, name='jwt'),
    path('api/refresh/', refresh_jwt_token, name='refresh'),

    path('api/products/', ProductListAPIView.as_view(), name='products_api'),
    path('api/products/<int:pk>/', ProductDetailAPIView.as_view(),
         name='products_detail_api'),
    path('api/products/new/', ProductCreateAPIView.as_view(), name='products_create_api'),
    path('api/products/<int:pk>/update/', ProductDetailUpdateAPIView.as_view(),
         name='products_detail_update_api'),

    path('api/categories/', CategoryListAPIView.as_view(), name='category_api'),
    path('api/categories/<int:pk>/', CategoryDetailAPIView.as_view(),
         name='category_detail_api'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create', views.order_create, name='order_create'),
    path('admin/order/<int:order_id>/pdf', views.admin_order_pdf, name='admin_order_pdf'),
]

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    override = forms.BooleanField(
        required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from catalog.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'], override_quantity=cd['override'])
    return redirect('cart:cart_detail')


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        quantity_form = {
            'quantity': item['quantity'],
            'override': True,
        }
        form = CartAddProductForm(initial=quantity_form)
        item['update_quantity_form'] = {
            'quantity': str(form['quantity']), 'override': str(form['override'])}
    return render(request, 'cart/detail.html', {'cart': cart})

templates/cart/detail.html
{% extends "base_catalog.html" %}
{% load i18n %}
{% load static %}

{% block title %} {% trans 'Your Cart' %} {% endblock %}
{% block content %} 
    <h1>{% trans 'Your Cart' %}</h1>
    <table class="cart">
        <thead>
            <tr>
                <th>{% trans 'Image' %}</th>
                <th>{% trans 'Product' %}</th>
                <th>{% trans 'Quantiy' %}</th>
                <th>{% trans 'Remove' %}</th>
                <th>{% trans 'Unit Price' %}</th>
                <th>{% trans 'Price' %}</th>
            </tr>
        </thead>
        <tbody>
            {% for item in cart %}
                {% with product=item.product %}
                    <tr>
                        <td>
                            <a href="{{ product.get_absolute_url }}">
                                <img src="{% if product.image %} {{ product.image }} {% else %} {% static "img/no-image-icon.png" %} {% endif %}" />
                            </a>
                        </td>
                        <td>
                            {{ product.name }}
                        </td>
                        <td>
                            <!--{{ item.quantity}}-->
                            <form action="{% url "cart:cart_add" product.id %}" method="post">
                                {{ item.update_quantity_form.quantity }}
                                {{ item.update_quantity_form.override }}
                                <input type="submit" value="{% trans "Update" %}" />
                                {% csrf_token %}
                            </form>
                        </td>
                        <td>
                            <form action="{% url "cart:cart_remove" product.id %}" method="post">
                                {% csrf_token %}
                                <input type="submit" value="{% trans "Remove" %}" />
                            </form>
                        </td>
                        <td>
                            {{ item.price }} €
                        </td>
                        <td>
                            {{ item.total_price }} €
                        </td>
                    </tr>
                {% endwith %}
            {% endfor %}
            <tr class="total">
                <td>{% trans "Total" %}</td>
                <td colspan="4"></td>
                <td>{{ cart.get_total_price }} €</td>
            </tr>
        </tbody>
    </table>
    <p>
        <a href="{% url "catalog:product_list" %}">{% trans "Continue shopping" %}</a>
        <a href="{% url "orders:order_create" %}">{% trans "Checkout" %}</a>
    </p>
{% endblock %}